"""Modify contact table

Revision ID: 121c93c96e12
Revises: 141f49d94604
Create Date: 2022-09-15 12:15:42.687325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121c93c96e12'
down_revision = '141f49d94604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_contact_phonenumber_key', 'contact', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contact_contact_phonenumber_key', 'contact', ['contact_phonenumber'])
    # ### end Alembic commands ###
