"""Create contact table

Revision ID: 141f49d94604
Revises: ccd28c10302e
Create Date: 2022-09-03 17:09:50.160963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141f49d94604'
down_revision = 'ccd28c10302e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=40), nullable=False),
    sa.Column('contact_phonenumber', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_phonenumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
